import { test, expect } from '@playwright/test';

// ── EN article (new template) /posts/2018-review-2019-goals/ ─────────────────
// Represents all translated EN articles generated by OpenAI (new navbar template)

test.describe('English article page (new template) /posts/2018-review-2019-goals/', () => {
  const URL = '/posts/2018-review-2019-goals/';

  test('page loads with status 200', async ({ page }) => {
    const res = await page.goto(URL);
    expect(res?.status()).toBe(200);
  });

  test('html lang is en', async ({ page }) => {
    await page.goto(URL);
    await expect(page.locator('html')).toHaveAttribute('lang', 'en');
  });

  test('page title contains article title and site name', async ({ page }) => {
    await page.goto(URL);
    const title = await page.title();
    expect(title).toContain('bmf-tech');
    expect(title.length).toBeGreaterThan('bmf-tech'.length);
  });

  test('navbar is present', async ({ page }) => {
    await page.goto(URL);
    await expect(page.locator('nav.navbar')).toBeVisible();
  });

  test('article h1 heading is visible', async ({ page }) => {
    await page.goto(URL);
    await expect(page.locator('h1').first()).toBeVisible();
  });

  test('article prose content is present and non-empty', async ({ page }) => {
    await page.goto(URL);
    const prose = page.locator('article.prose');
    await expect(prose).toBeVisible();
    const text = await prose.textContent();
    expect(text?.trim().length).toBeGreaterThan(0);
  });

  test('breadcrumbs are present and show Home', async ({ page }) => {
    await page.goto(URL);
    await expect(page.locator('.breadcrumbs')).toBeVisible();
    await expect(page.locator('.breadcrumbs-link').first()).toContainText('Home');
  });

  test('publication date is displayed', async ({ page }) => {
    await page.goto(URL);
    // New template: date shown as text-sm text-secondary span inside header
    await expect(page.locator('header .text-sm.text-secondary').first()).toBeVisible();
  });

  test('author name bmf-san is displayed', async ({ page }) => {
    await page.goto(URL);
    await expect(page.locator('header')).toContainText('bmf-san');
  });

  test('link to JA counterpart is present', async ({ page }) => {
    await page.goto(URL);
    const jaLink = page.locator('[lang="ja"]');
    await expect(jaLink).toBeVisible();
    const href = await jaLink.getAttribute('href');
    expect(href).toMatch(/^\/ja\/posts\//);
  });

  test('footer is present', async ({ page }) => {
    await page.goto(URL);
    await expect(page.locator('footer')).toBeVisible();
  });
});

// ── EN article (static/manual) /posts/hello-world/ ───────────────────────────
// hello-world is a manually created EN-only article using the standard template

test.describe('English article page /posts/hello-world/', () => {
  const URL = '/posts/hello-world/';

  test('page loads with status 200', async ({ page }) => {
    const res = await page.goto(URL);
    expect(res?.status()).toBe(200);
  });

  test('html lang is en', async ({ page }) => {
    await page.goto(URL);
    await expect(page.locator('html')).toHaveAttribute('lang', 'en');
  });

  test('page title is "Hello, World | bmf-tech"', async ({ page }) => {
    await page.goto(URL);
    await expect(page).toHaveTitle('Hello, World | bmf-tech');
  });

  test('article h1 heading is visible', async ({ page }) => {
    await page.goto(URL);
    await expect(page.locator('h1').first()).toBeVisible();
  });

  test('publication date is displayed', async ({ page }) => {
    await page.goto(URL);
    await expect(page.locator('header .text-sm.text-secondary').first()).toBeVisible();
  });

  test('article prose content is present and non-empty', async ({ page }) => {
    await page.goto(URL);
    const content = page.locator('article.prose');
    await expect(content).toBeVisible();
    const text = await content.textContent();
    expect(text?.trim().length).toBeGreaterThan(0);
  });

  test('navbar is present', async ({ page }) => {
    await page.goto(URL);
    await expect(page.locator('nav.navbar')).toBeVisible();
  });

  test('footer is present', async ({ page }) => {
    await page.goto(URL);
    await expect(page.locator('footer')).toBeVisible();
  });
});

// ── JA article /ja/posts/2018-review-2019-goals/ ─────────────────────────────

test.describe('Japanese article page /ja/posts/2018-review-2019-goals/', () => {
  const URL = '/ja/posts/2018-review-2019-goals/';

  test('page loads with status 200', async ({ page }) => {
    const res = await page.goto(URL);
    expect(res?.status()).toBe(200);
  });

  test('html lang is ja', async ({ page }) => {
    await page.goto(URL);
    await expect(page.locator('html')).toHaveAttribute('lang', 'ja');
  });

  test('page title contains article title and site name', async ({ page }) => {
    await page.goto(URL);
    const title = await page.title();
    expect(title).toContain('bmf-tech');
    expect(title.length).toBeGreaterThan('bmf-tech'.length);
  });

  test('navbar is present with Japanese labels', async ({ page }) => {
    await page.goto(URL);
    const nav = page.locator('nav.navbar');
    await expect(nav).toBeVisible();
    await expect(nav.getByRole('link', { name: 'ホーム' })).toBeVisible();
  });

  test('article h1 heading is visible', async ({ page }) => {
    await page.goto(URL);
    await expect(page.locator('h1').first()).toBeVisible();
  });

  test('article prose content is present and non-empty', async ({ page }) => {
    await page.goto(URL);
    const prose = page.locator('article.prose');
    await expect(prose).toBeVisible();
    const text = await prose.textContent();
    expect(text?.trim().length).toBeGreaterThan(0);
  });

  test('breadcrumbs show Home', async ({ page }) => {
    await page.goto(URL);
    await expect(page.locator('.breadcrumbs')).toBeVisible();
    await expect(page.locator('.breadcrumbs-link').first()).toContainText('Home');
  });

  test('link to EN counterpart is present', async ({ page }) => {
    await page.goto(URL);
    const enLink = page.locator('[lang="en"]');
    await expect(enLink).toBeVisible();
    const href = await enLink.getAttribute('href');
    expect(href).toMatch(/^\/posts\//);
  });

  test('category badge is visible in header', async ({ page }) => {
    await page.goto(URL);
    await expect(page.locator('header .badge-info').first()).toBeVisible();
  });

  test('footer is present', async ({ page }) => {
    await page.goto(URL);
    await expect(page.locator('footer')).toBeVisible();
  });
});
